


const Postdata = [
    
    {
        id:1,
        name:"Vaibhav Sharma",
        dp:"/images/dp/img1.jpg",
        image:"/images/Post_image/img1.jpg",
        title:"Lorem ipsum dolor sit amet, consectetur adipiscing",
        body:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vestibulum pulvinar diam, a porttitor velit. Donec consectetur massa et sem malesuada, non laoreet quam sollicitudin. Praesent et nibh augue. Cras lorem odio, elementum congue pretium ut, venenatis ac sem. Suspendisse ut tincidunt neque. Nam ac nulla tincidunt neque lacinia hendrerit. Ut leo quam, eleifend quis lorem vitae, semper varius ex. In hac habitasse platea dictumst. Vestibulum nec gravida libero. Proin gravida, ligula non tristique facilisis, sapien est imperdiet erat, quis euismod nulla nibh ut enim. Suspendisse elementum justo nec nunc congue, in cursus odio facilisis. Cras id quam non elit aliquet tincidunt. Quisque quis pretium justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus sodales hendrerit elementum.<br/Donec vehicula congue eros, sit amet lobortis ipsum pharetra id. Proin efficitur enim tellus, nec fermentum ante volutpat sit amet. Nullam iaculis placerat ultrices. Proin diam lectus, sagittis quis rhoncus in, porttitor in lorem. Maecenas maximus ultricies nisi maximus suscipit. Pellentesque mauris felis, placerat ac ligula fermentum, venenatis consequat neque. Duis et quam urna. Aenean eget sagittis purus. Aliquam ut sapien consequat, iaculis lorem vel, lobortis quam. Nullam condimentum ornare varius.<br/>Cras nec enim turpis. Quisque ex augue, maximus in augue eu, hendrerit bibendum tellus. Quisque vehicula ipsum sit amet faucibus tincidunt. Etiam ut lobortis ipsum. Sed pulvinar sit amet nisi non fringilla. Cras id ipsum lacinia, consequat neque ut, efficitur dolor. Vivamus feugiat in lacus a sollicitudin.<br/>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas tincidunt enim ut justo gravida, id egestas purus bibendum. Praesent varius volutpat risus, at viverra felis lacinia non. Donec cursus interdum mauris non pharetra. Morbi vitae ullamcorper turpis, ac tempus libero. Integer feugiat eros in tincidunt vestibulum. Vestibulum eu tempus urna. Etiam mattis nisi libero, sed sodales quam dapibus at. Suspendisse non iaculis quam, a tempus sem. Aliquam porttitor fermentum ex sit amet sollicitudin. Vivamus eget elementum quam, a pellentesque ipsum. Vestibulum id leo sed velit pulvinar accumsan. Mauris blandit scelerisque mauris, et aliquet arcu dictum id. Aenean vitae gravida arcu. Curabitur condimentum eleifend ligula et bibendum. Proin iaculis nunc non dolor eleifend commodo.",
        date:"14 May 2023"
    },
    {
        id:2,
        name:"Ujjwal",
        dp:"/images/dp/img2.jpg",
        image:"/images/Post_image/img2.jpg",
        title:"Lorem ipsum dolor sit amet, consectetur adipiscing",
        body:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vestibulum pulvinar diam, a porttitor velit. Donec consectetur massa et sem malesuada, non laoreet quam sollicitudin. Praesent et nibh augue. Cras lorem odio, elementum congue pretium ut, venenatis ac sem. Suspendisse ut tincidunt neque. Nam ac nulla tincidunt neque lacinia hendrerit. Ut leo quam, eleifend quis lorem vitae, semper varius ex. In hac habitasse platea dictumst. Vestibulum nec gravida libero. Proin gravida, ligula non tristique facilisis, sapien est imperdiet erat, quis euismod nulla nibh ut enim. Suspendisse elementum justo nec nunc congue, in cursus odio facilisis. Cras id quam non elit aliquet tincidunt. Quisque quis pretium justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus sodales hendrerit elementum.<br/Donec vehicula congue eros, sit amet lobortis ipsum pharetra id. Proin efficitur enim tellus, nec fermentum ante volutpat sit amet. Nullam iaculis placerat ultrices. Proin diam lectus, sagittis quis rhoncus in, porttitor in lorem. Maecenas maximus ultricies nisi maximus suscipit. Pellentesque mauris felis, placerat ac ligula fermentum, venenatis consequat neque. Duis et quam urna. Aenean eget sagittis purus. Aliquam ut sapien consequat, iaculis lorem vel, lobortis quam. Nullam condimentum ornare varius.<br/>Cras nec enim turpis. Quisque ex augue, maximus in augue eu, hendrerit bibendum tellus. Quisque vehicula ipsum sit amet faucibus tincidunt. Etiam ut lobortis ipsum. Sed pulvinar sit amet nisi non fringilla. Cras id ipsum lacinia, consequat neque ut, efficitur dolor. Vivamus feugiat in lacus a sollicitudin.<br/>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas tincidunt enim ut justo gravida, id egestas purus bibendum. Praesent varius volutpat risus, at viverra felis lacinia non. Donec cursus interdum mauris non pharetra. Morbi vitae ullamcorper turpis, ac tempus libero. Integer feugiat eros in tincidunt vestibulum. Vestibulum eu tempus urna. Etiam mattis nisi libero, sed sodales quam dapibus at. Suspendisse non iaculis quam, a tempus sem. Aliquam porttitor fermentum ex sit amet sollicitudin. Vivamus eget elementum quam, a pellentesque ipsum. Vestibulum id leo sed velit pulvinar accumsan. Mauris blandit scelerisque mauris, et aliquet arcu dictum id. Aenean vitae gravida arcu. Curabitur condimentum eleifend ligula et bibendum. Proin iaculis nunc non dolor eleifend commodo.",
        date:"14 May 2023"
    },
    {
        id:3,
        name:"Sumit Saini",
        dp:"/images/dp/img3.jpg",
        image:"/images/Post_image/img3.jpg",
        title:"Lorem ipsum dolor sit amet, consectetur adipiscing",
        body:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vestibulum pulvinar diam, a porttitor velit. Donec consectetur massa et sem malesuada, non laoreet quam sollicitudin. Praesent et nibh augue. Cras lorem odio, elementum congue pretium ut, venenatis ac sem. Suspendisse ut tincidunt neque. Nam ac nulla tincidunt neque lacinia hendrerit. Ut leo quam, eleifend quis lorem vitae, semper varius ex. In hac habitasse platea dictumst. Vestibulum nec gravida libero. Proin gravida, ligula non tristique facilisis, sapien est imperdiet erat, quis euismod nulla nibh ut enim. Suspendisse elementum justo nec nunc congue, in cursus odio facilisis. Cras id quam non elit aliquet tincidunt. Quisque quis pretium justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus sodales hendrerit elementum.<br/Donec vehicula congue eros, sit amet lobortis ipsum pharetra id. Proin efficitur enim tellus, nec fermentum ante volutpat sit amet. Nullam iaculis placerat ultrices. Proin diam lectus, sagittis quis rhoncus in, porttitor in lorem. Maecenas maximus ultricies nisi maximus suscipit. Pellentesque mauris felis, placerat ac ligula fermentum, venenatis consequat neque. Duis et quam urna. Aenean eget sagittis purus. Aliquam ut sapien consequat, iaculis lorem vel, lobortis quam. Nullam condimentum ornare varius.<br/>Cras nec enim turpis. Quisque ex augue, maximus in augue eu, hendrerit bibendum tellus. Quisque vehicula ipsum sit amet faucibus tincidunt. Etiam ut lobortis ipsum. Sed pulvinar sit amet nisi non fringilla. Cras id ipsum lacinia, consequat neque ut, efficitur dolor. Vivamus feugiat in lacus a sollicitudin.<br/>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas tincidunt enim ut justo gravida, id egestas purus bibendum. Praesent varius volutpat risus, at viverra felis lacinia non. Donec cursus interdum mauris non pharetra. Morbi vitae ullamcorper turpis, ac tempus libero. Integer feugiat eros in tincidunt vestibulum. Vestibulum eu tempus urna. Etiam mattis nisi libero, sed sodales quam dapibus at. Suspendisse non iaculis quam, a tempus sem. Aliquam porttitor fermentum ex sit amet sollicitudin. Vivamus eget elementum quam, a pellentesque ipsum. Vestibulum id leo sed velit pulvinar accumsan. Mauris blandit scelerisque mauris, et aliquet arcu dictum id. Aenean vitae gravida arcu. Curabitur condimentum eleifend ligula et bibendum. Proin iaculis nunc non dolor eleifend commodo.",
        date:"14 May 2023"
    },
    {
        id:4,
        name:"Sauvit Gan Chodhri",
        dp:"/images/dp/img4.jpg",
        image:"/images/Post_image/img4.jpg",
        title:"Lorem ipsum dolor sit amet, consectetur adipiscing",
        body:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vestibulum pulvinar diam, a porttitor velit. Donec consectetur massa et sem malesuada, non laoreet quam sollicitudin. Praesent et nibh augue. Cras lorem odio, elementum congue pretium ut, venenatis ac sem. Suspendisse ut tincidunt neque. Nam ac nulla tincidunt neque lacinia hendrerit. Ut leo quam, eleifend quis lorem vitae, semper varius ex. In hac habitasse platea dictumst. Vestibulum nec gravida libero. Proin gravida, ligula non tristique facilisis, sapien est imperdiet erat, quis euismod nulla nibh ut enim. Suspendisse elementum justo nec nunc congue, in cursus odio facilisis. Cras id quam non elit aliquet tincidunt. Quisque quis pretium justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus sodales hendrerit elementum.<br/Donec vehicula congue eros, sit amet lobortis ipsum pharetra id. Proin efficitur enim tellus, nec fermentum ante volutpat sit amet. Nullam iaculis placerat ultrices. Proin diam lectus, sagittis quis rhoncus in, porttitor in lorem. Maecenas maximus ultricies nisi maximus suscipit. Pellentesque mauris felis, placerat ac ligula fermentum, venenatis consequat neque. Duis et quam urna. Aenean eget sagittis purus. Aliquam ut sapien consequat, iaculis lorem vel, lobortis quam. Nullam condimentum ornare varius.<br/>Cras nec enim turpis. Quisque ex augue, maximus in augue eu, hendrerit bibendum tellus. Quisque vehicula ipsum sit amet faucibus tincidunt. Etiam ut lobortis ipsum. Sed pulvinar sit amet nisi non fringilla. Cras id ipsum lacinia, consequat neque ut, efficitur dolor. Vivamus feugiat in lacus a sollicitudin.<br/>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas tincidunt enim ut justo gravida, id egestas purus bibendum. Praesent varius volutpat risus, at viverra felis lacinia non. Donec cursus interdum mauris non pharetra. Morbi vitae ullamcorper turpis, ac tempus libero. Integer feugiat eros in tincidunt vestibulum. Vestibulum eu tempus urna. Etiam mattis nisi libero, sed sodales quam dapibus at. Suspendisse non iaculis quam, a tempus sem. Aliquam porttitor fermentum ex sit amet sollicitudin. Vivamus eget elementum quam, a pellentesque ipsum. Vestibulum id leo sed velit pulvinar accumsan. Mauris blandit scelerisque mauris, et aliquet arcu dictum id. Aenean vitae gravida arcu. Curabitur condimentum eleifend ligula et bibendum. Proin iaculis nunc non dolor eleifend commodo.",
        date:"14 May 2023"
    },
    {
        id:5,
        name:"Sakshi",
        dp:"/images/dp/img5.jpg",
        image:"/images/Post_image/img5.jpg",
        title:"Lorem ipsum dolor sit amet, consectetur adipiscing",
        body:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vestibulum pulvinar diam, a porttitor velit. Donec consectetur massa et sem malesuada, non laoreet quam sollicitudin. Praesent et nibh augue. Cras lorem odio, elementum congue pretium ut, venenatis ac sem. Suspendisse ut tincidunt neque. Nam ac nulla tincidunt neque lacinia hendrerit. Ut leo quam, eleifend quis lorem vitae, semper varius ex. In hac habitasse platea dictumst. Vestibulum nec gravida libero. Proin gravida, ligula non tristique facilisis, sapien est imperdiet erat, quis euismod nulla nibh ut enim. Suspendisse elementum justo nec nunc congue, in cursus odio facilisis. Cras id quam non elit aliquet tincidunt. Quisque quis pretium justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus sodales hendrerit elementum.<br/Donec vehicula congue eros, sit amet lobortis ipsum pharetra id. Proin efficitur enim tellus, nec fermentum ante volutpat sit amet. Nullam iaculis placerat ultrices. Proin diam lectus, sagittis quis rhoncus in, porttitor in lorem. Maecenas maximus ultricies nisi maximus suscipit. Pellentesque mauris felis, placerat ac ligula fermentum, venenatis consequat neque. Duis et quam urna. Aenean eget sagittis purus. Aliquam ut sapien consequat, iaculis lorem vel, lobortis quam. Nullam condimentum ornare varius.<br/>Cras nec enim turpis. Quisque ex augue, maximus in augue eu, hendrerit bibendum tellus. Quisque vehicula ipsum sit amet faucibus tincidunt. Etiam ut lobortis ipsum. Sed pulvinar sit amet nisi non fringilla. Cras id ipsum lacinia, consequat neque ut, efficitur dolor. Vivamus feugiat in lacus a sollicitudin.<br/>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas tincidunt enim ut justo gravida, id egestas purus bibendum. Praesent varius volutpat risus, at viverra felis lacinia non. Donec cursus interdum mauris non pharetra. Morbi vitae ullamcorper turpis, ac tempus libero. Integer feugiat eros in tincidunt vestibulum. Vestibulum eu tempus urna. Etiam mattis nisi libero, sed sodales quam dapibus at. Suspendisse non iaculis quam, a tempus sem. Aliquam porttitor fermentum ex sit amet sollicitudin. Vivamus eget elementum quam, a pellentesque ipsum. Vestibulum id leo sed velit pulvinar accumsan. Mauris blandit scelerisque mauris, et aliquet arcu dictum id. Aenean vitae gravida arcu. Curabitur condimentum eleifend ligula et bibendum. Proin iaculis nunc non dolor eleifend commodo.",
        date:"14 May 2023"
    },
    {
        id:6,
        name:"Kanika Kainthla",
        dp:"/images/dp/img6.jpg",
        image:"/images/Post_image/img6.jpg",
        title:"Lorem ipsum dolor sit amet, consectetur adipiscing",
        body:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vestibulum pulvinar diam, a porttitor velit. Donec consectetur massa et sem malesuada, non laoreet quam sollicitudin. Praesent et nibh augue. Cras lorem odio, elementum congue pretium ut, venenatis ac sem. Suspendisse ut tincidunt neque. Nam ac nulla tincidunt neque lacinia hendrerit. Ut leo quam, eleifend quis lorem vitae, semper varius ex. In hac habitasse platea dictumst. Vestibulum nec gravida libero. Proin gravida, ligula non tristique facilisis, sapien est imperdiet erat, quis euismod nulla nibh ut enim. Suspendisse elementum justo nec nunc congue, in cursus odio facilisis. Cras id quam non elit aliquet tincidunt. Quisque quis pretium justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus sodales hendrerit elementum.<br/Donec vehicula congue eros, sit amet lobortis ipsum pharetra id. Proin efficitur enim tellus, nec fermentum ante volutpat sit amet. Nullam iaculis placerat ultrices. Proin diam lectus, sagittis quis rhoncus in, porttitor in lorem. Maecenas maximus ultricies nisi maximus suscipit. Pellentesque mauris felis, placerat ac ligula fermentum, venenatis consequat neque. Duis et quam urna. Aenean eget sagittis purus. Aliquam ut sapien consequat, iaculis lorem vel, lobortis quam. Nullam condimentum ornare varius.<br/>Cras nec enim turpis. Quisque ex augue, maximus in augue eu, hendrerit bibendum tellus. Quisque vehicula ipsum sit amet faucibus tincidunt. Etiam ut lobortis ipsum. Sed pulvinar sit amet nisi non fringilla. Cras id ipsum lacinia, consequat neque ut, efficitur dolor. Vivamus feugiat in lacus a sollicitudin.<br/>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas tincidunt enim ut justo gravida, id egestas purus bibendum. Praesent varius volutpat risus, at viverra felis lacinia non. Donec cursus interdum mauris non pharetra. Morbi vitae ullamcorper turpis, ac tempus libero. Integer feugiat eros in tincidunt vestibulum. Vestibulum eu tempus urna. Etiam mattis nisi libero, sed sodales quam dapibus at. Suspendisse non iaculis quam, a tempus sem. Aliquam porttitor fermentum ex sit amet sollicitudin. Vivamus eget elementum quam, a pellentesque ipsum. Vestibulum id leo sed velit pulvinar accumsan. Mauris blandit scelerisque mauris, et aliquet arcu dictum id. Aenean vitae gravida arcu. Curabitur condimentum eleifend ligula et bibendum. Proin iaculis nunc non dolor eleifend commodo.",
        date:"14 May 2023"
    },
    {
        id:7,
        name:"Nandini Sharma",
        dp:"/images/dp/img7.jpg",
        image:"/images/Post_image/img7.jpg",
        title:"Lorem ipsum dolor sit amet, consectetur adipiscing",
        body:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vestibulum pulvinar diam, a porttitor velit. Donec consectetur massa et sem malesuada, non laoreet quam sollicitudin. Praesent et nibh augue. Cras lorem odio, elementum congue pretium ut, venenatis ac sem. Suspendisse ut tincidunt neque. Nam ac nulla tincidunt neque lacinia hendrerit. Ut leo quam, eleifend quis lorem vitae, semper varius ex. In hac habitasse platea dictumst. Vestibulum nec gravida libero. Proin gravida, ligula non tristique facilisis, sapien est imperdiet erat, quis euismod nulla nibh ut enim. Suspendisse elementum justo nec nunc congue, in cursus odio facilisis. Cras id quam non elit aliquet tincidunt. Quisque quis pretium justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus sodales hendrerit elementum.<br/Donec vehicula congue eros, sit amet lobortis ipsum pharetra id. Proin efficitur enim tellus, nec fermentum ante volutpat sit amet. Nullam iaculis placerat ultrices. Proin diam lectus, sagittis quis rhoncus in, porttitor in lorem. Maecenas maximus ultricies nisi maximus suscipit. Pellentesque mauris felis, placerat ac ligula fermentum, venenatis consequat neque. Duis et quam urna. Aenean eget sagittis purus. Aliquam ut sapien consequat, iaculis lorem vel, lobortis quam. Nullam condimentum ornare varius.<br/>Cras nec enim turpis. Quisque ex augue, maximus in augue eu, hendrerit bibendum tellus. Quisque vehicula ipsum sit amet faucibus tincidunt. Etiam ut lobortis ipsum. Sed pulvinar sit amet nisi non fringilla. Cras id ipsum lacinia, consequat neque ut, efficitur dolor. Vivamus feugiat in lacus a sollicitudin.<br/>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas tincidunt enim ut justo gravida, id egestas purus bibendum. Praesent varius volutpat risus, at viverra felis lacinia non. Donec cursus interdum mauris non pharetra. Morbi vitae ullamcorper turpis, ac tempus libero. Integer feugiat eros in tincidunt vestibulum. Vestibulum eu tempus urna. Etiam mattis nisi libero, sed sodales quam dapibus at. Suspendisse non iaculis quam, a tempus sem. Aliquam porttitor fermentum ex sit amet sollicitudin. Vivamus eget elementum quam, a pellentesque ipsum. Vestibulum id leo sed velit pulvinar accumsan. Mauris blandit scelerisque mauris, et aliquet arcu dictum id. Aenean vitae gravida arcu. Curabitur condimentum eleifend ligula et bibendum. Proin iaculis nunc non dolor eleifend commodo.",
        date:"14 May 2023"
    },

]

export default Postdata;